[window]
opacity = 0.8

dimensions = { columns = 120, lines = 30}

padding = {x = 20, y = 10}

[font]
normal = { family = "Fira Code Nerd Font", style = "Regular"}
bold = {family = "Fira Code Nerd Font", style = "Bold"}
italic = {family = "Fira Code Nerd Font", style = "Italic"}
bold_italic = {family = "Fira Code Nerd Font", style = "Bold Italic"}

size = 20

[cursor]
style = {shape = "Block", blinking = "On"}
